name: cpplint
on: [push, pull_request]
jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: pip install cpplint
    - run: cpplint --recursive --filter=-legal/copyright,-build/header_guard,-build/c++11,-build/include,-runtime/references ./src
